In [ ]:
# Library
# https://gymnasium.farama.org/environments/toy_text/frozen_lake/
# odev
# https://gymnasium.farama.org/environments/toy_text/cliff_walking/

# import gym
import gymnasium as gym
import numpy as np

# is_slippery=False yaparak ajanin buzlu alanda kaymasini engelliyoruz
environment = gym.make("FrozenLake-v1", is_slippery=False, render_mode="ansi")
environment.reset() # (0, {'prob': 1})

nb_states = environment.observation_space.n # np.int64(16)
nb_actions = environment.action_space.n # np.int64(4)
qtable = np.zeros((nb_states, nb_actions))

print("Q-table :")
print(qtable)

action = environment.action_space.sample() # random action gerceklesir
"""
sol : 0
aşağı : 1
sağ : 2
yukarı : 3
"""

# S1 -> (Action 1) -> S2
new_state, reward, done, info, _ = environment.step(action)

Q-table :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
